### ISSUE TITLE
Require Node.js 4?

### ISSUE THREAD

**Issue by hugojosefson** [mikaelbr/bacon-love#10]
_This does not apply to the latest release on npm, but only to the `master` branch, and should be resolved before releasing the next version._

When running `bacon-love run` or `bacon-love verify` under Node.js 0.12, it works fine if the user's program only uses ES5. However, if the user follows the instructions given and uses ES2015 language features in their program, they get this non-helpful error:

```
✗ Could not find your file. Make sure the path is correct.
```

What should happen, is to either give them a better error message, or simply require Node.js >=4 to run `bacon-love` at all.

I think it will be non-trivial to handle the error correctly, because it has to do with Babel and how it handles the user's file. My recommendation is that we add a hard requirement on Node.js >=4. What do you think @mikaelbr?

**Comment by mikaelbr** [comment]
I think we safely can require newer node versions also. rather that then babel in my opinion. I think most users of this use newer versions.

**Comment by hugojosefson** [comment]
Alright, I'll get on it :)
