### ISSUE TITLE
Adding this to NodeSchool.io

### ISSUE THREAD

**Issue by finnp** [mikaelbr/bacon-love#3]
Hey,

how about adding this to the NodeSchool page? There's no reactive workshopper yet.

Best,
Finn

**Comment by mikaelbr** [comment]
Hi! We had a plan of doing this, but we were thinking of revising some of the text and task before we posted it. Then again, by posting it we might get help and feedback for what needs revising.

**Comment by hugojosefson** [comment]
For reference, I looked into how to go about submitting a workshopper to [nodeschool.io](http://nodeschool.io), and it looks like we can send a Pull Request changing files like this: https://github.com/nodeschool/nodeschool.github.io/commit/2b33238c3ef038a2757aa09f3ff2c8e8b9c8bec0

**Comment by mikaelbr** [comment]
@hugojosefson Did you ever get around doing this? Or should someone just open a PR?

**Comment by hugojosefson** [comment]
@mikaelbr I didn't. Someone can definitely go ahead and open a pull request on nodeschool, for example  based on the details I put in my comment above! :) Unfortunately I don't have the time now...

**Comment by mikaelbr** [comment]
Done and done: https://github.com/nodeschool/nodeschool.github.io/pull/523

**Comment by hugojosefson** [comment]
Thanks @mikaelbr!
