### ISSUE TITLE
Content license for bacon-love?

### ISSUE THREAD

**Issue by joelhooks** [mikaelbr/bacon-love#8]
Hi @mikaelbr, really love what you've put together. I was wondering how this content was licensed, and if it would be OK to create a derivative work using RxJS?

**Comment by mikaelbr** [comment]
Hi! Feel free to use the content for a RxJS-workshop! The content is the same license as the repo (MIT). If you'd like you can link to this workshop. No requirement of course, just for our love of Bacon ≈ :cake:

**Comment by joelhooks** [comment]
@mikaelbr thanks!
